# Generated by Django 3.2.7 on 2022-08-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='concern',
            new_name='passconcern',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='passemail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='passname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='passphone',
        ),
    ]
