# Generated by Django 3.2.7 on 2022-08-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220812_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='passconcern',
            new_name='concern',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='passemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='passname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='passphone',
            new_name='phone',
        ),
    ]
