# Generated by Django 3.2.7 on 2022-08-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220812_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='concern',
            field=models.TextField(max_length=100),
        ),
    ]
